server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/pr19
    username: postgres
    password: Dron0p4Ka
    driverClassName: org.postgresql.Driver